server:
  port: 8082
  servlet:
    context-path: /produto
   
spring:
  application:
    name: produto
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect 
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/produto?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: example
  
  rabbitmq:
    host: localhost 
    port: 5672
    username: admin
    password: admin 
    
produto:
  rabbitmq:
    exchange: produto.exchange
    routingkey: produto.produto.routingkey
    
security:
  jwt:
    token: 
      secret-key: chave_microservices
      
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
          