server:
  port: 8079
    
spring:
  application:
    name: gateway
    
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000   
      
zuul:
  prefix: /api
  ignored-services: "*"
  
  routes:
    produto:
      path: /produto/**
      service-id: produto
      strip-prefix: false
      custom-sensitive-headers: true
      
    catalogo:
      path: /catalogo/**
      service-id: catalogo
      strip-prefix: false
      custom-sensitive-headers: true
      
    pagamento:
      path: /pagamento/**
      service-id: pagamento
      strip-prefix: false
      custom-sensitive-headers: true
      
    auth:
      path: /auth/**
      service-id: auth
      strip-prefix: false
      custom-sensitive-headers: true           
                  
