spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/BrandaoDeSerra/java-ms-rabbit-queue/tree/main/config-server-resources
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
server:
  port: 8888
          
